### ISSUE TITLE
Touches

### ISSUE THREAD

**Issue by zdnk** [dave-redfern/laravel-doctrine-behaviours#1]
Hello,

would it be possible to implements something like Eloquents `$touches` in models?
Sou you can update updateAt timestamp of parent or related entity.

**Comment by dave-redfern** [comment]
@zdenektopic Apologies for the delay in responding, I didn't get a notice about your comment. I'm in the middle of refactoring the extension and part of that is moving to an initializeTimestamps() / updateTimestamps() methodology and factoring out the setters. Unfortunately that would not address updating parent entities because from Doctrines perspective the parent has not been changed. The Gedmo extension might be able to do this.

I can think of several alternative implementations though:

- a more expensive alternative would be to hook preFlush and for all Timestampable objects currently in the entity manager, update them,
- add a secondary event subscriber with a separate interface (maybe something like ForceUpdateTimestamps or similar) that always runs,
- or if a child has a parent flagged with a specific interface, do something similar. Again that means hunting through the changed entities looking for parent objects and if your UoW is large could be a bit clunky.

As an alternative: you could look at doing away entirely with the event listeners and implementing the logic through the parent and treating it as an Aggregate Root. That way you load the parent initially, and call the update method on that and have the changes propagated into the child. Something similar to adding Groups to a User. That way you have total control over what happens and what triggers a change, but it does mean a more DDD approach to your code.

I can certainly look at implementing a secondary listener that can cascade update parents.
